spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/concert_reservation
    username: root
    password: password
  jpa:
#    hibernate:
#      ddl-auto: create
    #    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      port: 6379
      host: redis
  cache:
    type: redis

kafka:
  producer:
    bootstrap-servers: kafka1:9092
  consumer:
    bootstrap-servers: kafka1:9092
    auto-offset-reset: earliest
  topics:
    payment: payment-done-topic
  groups:
    payment: payment-group
    waitingQueue: waiting-queue-group
    notification: notification-group

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true