spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concert_reservation
    username: root
    password: pcs8437!
  jpa:
    hibernate:
#      ddl-auto: create
    #    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis

kafka:
  producer:
    bootstrap-servers: localhost:29092
  consumer:
    bootstrap-servers: localhost:29092
    auto-offset-reset: earliest
  topics:
    payment: payment-done-topic
  groups:
    payment: payment-group
    waitingQueue: waiting-queue-group
    notification: notification-group